version: 2
updates:
  - package-ecosystem: "pip"
    directory: "docs/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"