site_name: Kubeflare Docs
theme:
  name: material
markdown_extensions:
  - admonition
nav:
  - Getting Started:
      - 'Introduction': 'index.md'
      - 'Cloudflare API Support': 'getting-started/api-support.md'
      - 'Importing': 'getting-started/importing.md'
  - Installing:
      - 'Install with kubectl': 'install/kubectl.md'
      - 'Install with Helm': 'install/helm.md'
  - API:
      - 'APIToken': 'api/apitoken.md'
      - 'Zone': 'api/zone.md'
      - 'DNSRecord': 'api/dnsrecord.md'
      - 'PageRules': 'api/pagerules.md'
      - 'WAFRules': 'api/wafrules.md'
